############################################################
# +------------------------------------------------------+ #
# |                                                      | #
# |           FactionShields Plugin Configuration        | #
# |                  Made By Benzimmer                   | #
# |                                                      | #
# +------------------------------------------------------+ #
############################################################
  
send-land-enter-msg: true # Send message if shield is active
  
shield-check: 60 # Shield check task  
cooldown-period: 60000 # In seconds (Set to -1 to disable)

# When shield is active:
prevent-creeper-damage: true # Prevent Creeper Damage
prevent-tnt-damage: true # Prevent TNT Damage
prevent-team-damage: false  # Prevent Team Damage (Only in team land)

# List of timezones can be found here https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# Any spaces in a timezone should be used as an "_"

current-timezone: Europe/London

main_gui:
  title: '&c&lFaction Shield Status'
  size: 27
  items:
    dummy-item-1:
      type: STAINED_GLASS_PANE
      data: 15
      amount: 1
      name: ' '
      lore:
      -
      slots:
      - 0
      - 2
      - 4
      - 6
      - 8
      - 10
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
      - 24
      - 26
    dummy-item-2:
      type: STAINED_GLASS_PANE
      data: 14
      amount: 1
      name: ' '
      lore:
      -
      slots:
      - 1
      - 3
      - 5
      - 7
      - 9
      - 13
      - 17
      - 19
      - 21
      - 23
      - 25
    status:
      type: BANNER
      data: 0
      amount: 1
      name: '&aFaction Shield Status'
      lore:
      - '&7Status > %status%'
      - '&7Start Time > &a%starttime%'
      - '&7End Time > &a%endtime%'
      slots:
      - 15
    purchase:
      type: DIAMOND_CHESTPLATE
      data: 0
      amount: 1
      name: '&aPurchase Shields'
      lore:
      - '&7> View all purchasable shield times'
      slots:
      - 11
      
purchase_gui:
  title: '&2&lPurchase Shields'
  size: 36 
  time_items: # Add your own items here (Need to be 24 format times)
    1:
      start_time: '1:00'
      end_time: '3:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a1AM-3AM'
      lore:
      - '&7Purchase a Shield for 1am-3am.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 10
    2:
      start_time: '3:00'
      end_time: '5:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a3AM-5AM'
      lore:
      - '&7Purchase a Shield for 3am-5am.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 11
    3:
      start_time: '5:00'
      end_time: '7:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a5AM-7AM'
      lore:
      - '&7Purchase a Shield for 5am-7am.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 12
    4:
      start_time: '7:00'
      end_time: '9:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a7AM-9AM'
      lore:
      - '&7Purchase a Shield for 7am-9am.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 13
    5:
      start_time: '9:00'
      end_time: '11:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a9AM-11AM'
      lore:
      - '&7Purchase a Shield for 9am-11am.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 14
    6:
      start_time: '11:00'
      end_time: '13:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a11AM-1PM'
      lore:
      - '&7Purchase a Shield for 11am-1pm.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 15
    7:
      start_time: '13:00'
      end_time: '15:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a1PM-3PM'
      lore:
      - '&7Purchase a Shield for 1pm-3pm.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 16
    8:
      start_time: '15:00'
      end_time: '17:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a3PM-5PM'
      lore:
      - '&7Purchase a Shield for 3pm-5pm.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 19
    9:
      start_time: '17:00'
      end_time: '19:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a5PM-7PM'
      lore:
      - '&7Purchase a Shield for 5pm-7pm.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 20
    10:
      start_time: '19:00'
      end_time: '21:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a7PM-9PM'
      lore:
      - '&7Purchase a Shield for 7pm-9pm.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 21
    11:
      start_time: '21:00'
      end_time: '23:00' 
      cost: 10000
      type: WATCH
      data: 0
      amount: 1
      name: '&a9PM-11PM'
      lore:
      - '&7Purchase a Shield for 9pm-11pm.'
      - '&7This will cost &a$10000&7.'
      slots:
      - 22
  default_items:
    dummy-item-1:
      type: STAINED_GLASS_PANE
      data: 15
      amount: 1
      name: ' '
      lore:
      -
      slots:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 17
      - 18
      - 26
      - 27
      - 28
      - 29
      - 30
      - 31
      - 32
      - 33
      - 34
    dummy-item-2:
      type: STAINED_GLASS_PANE
      data: 0
      amount: 1
      name: ' '
      lore:
      -
      slots:
    back:
      type: ARROW
      data: 0
      amount: 1
      name: '&aGo Back'
      lore:
      - '&7Click to go back'
      slots:
      - 35